networks:
  mynet:
    driver: bridge

services:
  web:
    build: ./web/
    ports:
      - "80-81:80"
    deploy:
      mode: replicate
      replicas: 2
      resources:
        limits:
          cpus: '1.00'
          memory: 100M
    links:
      - banco:banco
    networks:
      mynet:

  banco:
    build: ./sql/
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: lamp
      MYSQL_USER: user_lamp
      MYSQL_PASSWORD: lamp_pass
    networks:
      mynet:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
    links:
      - banco:banco
    networks:
      mynet:
