# Configurando Rede dos Serviços
networks:
  mynet:
    driver: bridge

# Configurando os Serviços
services:
  web: # Serviço Web
    build: .
    ports:
      - "80:80"
    links:
      - banco:banco
    networks:
      mynet:

  banco: # Banco de dados
    build: ./sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: lamp
      MYSQL_USER: user_lamp
      MYSQL_PASSWORD: lamp_pass
    networks:
      mynet:

  adminer: # Gerenciador de banco
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - banco:banco
    networks:
      mynet: