version: "2"

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - banco:banco
    volumes:
      - $PWD:/var/www/html
    networks:
      mynet:
       ipv4_address: 172.18.0.2

  banco:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: lamp
      MYSQL_USER: user_lamp
      MYSQL_PASSWORD: lamp_pass
    networks:
      mynet:
        ipv4_address: 172.18.0.3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - banco:banco
    networks:
      mynet:
        ipv4_address: 172.18.0.4

# jdbc:mysql://localhost:3306/lamp?allowPublicKeyRetrieval=true&useSSL=false